#page title
page_title                                : AI Assistant App                              # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                   # Required. Enter iOS app ID to automatically populate name, price and icons.
ios_app_country                           : us                                           # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : # Add the iOS App Store link once available.
playstore_link                            : https://play.google.com/store/apps/details?id=com.yourapp.aiassistant     # Enter Google Play Store URL.
presskit_download_link                    : https://yourwebsite.com/press-kit.zip         # Enter a link to a downloadable press kit file or public Dropbox link.

app_icon                                  : assets/appicon.png                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter path to icon file manually.
app_name                                  : AI Assistant App                             # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
app_price                                 : Free                                         # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
app_description                           : Engage with AI for chat, image generation, and language translation in multiple languages.

enable_smart_app_banner                   : true                                         # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Ardit Konjuhi                                # Update your information.
your_link                                 : https://yourwebsite.com
your_city                                 : Prishtina
email_address                             : arditkonjuhi8@gmail.com
facebook_username                         : your_facebook_username
instagram_username                        : your_instagram_username
twitter_username                          : your_twitter_username
github_username                           : arditkonjuhi
youtube_username                          : your_youtube_username
mastodon_link                             : # Add Mastodon link if relevant.

# Feature List                            Edit, add or remove features to be presented.
features                                  :
  - title                                 : AI Chat with Gemini
    description                           : Engage in conversations with an AI assistant powered by Gemini.
    fontawesome_icon_name                 : robot

  - title                                 : AI Image Generation
    description                           : Generate AI-based images using the Unsplash API.
    fontawesome_icon_name                 : image

  - title                                 : Language Translation
    description                           : Translate text between multiple languages such as English, Albanian, Slovenian, and German.
    fontawesome_icon_name                 : language

  - title                                 : User Authentication
    description                           : Secure user authentication with Firebase.
    fontawesome_icon_name                 : lock

  - title                                 : Chat & Image Management
    description                           : Manage chat history, generated images, and translation history with ease.
    fontawesome_icon_name                 : tasks

  - title                                 : Translation History
    description                           : Access past translations and apply filters to view specific languages.
    fontawesome_icon_name                 : history

  - title                                 : Smart App Banner
    description                           : Display a smart app banner on iOS devices.
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : Social Links
    description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : link

  - title                                 : FontAwesome Support
    description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : info-circle

  - title                                 : Realtime Updates
    description                           : Receive realtime updates for chat, images, and translation history with Firebase Firestore.
    fontawesome_icon_name                 : sync



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"



####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
